---
name: Telegraf
version: 0.0.2
slug: hassio_telegraf
description: A cross-platform system monitoring tool
url: https://github.com/conrad784/hassio-telegraf
panel_icon: mdi:speedometer
startup: services
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - addons
  - backup
  - config:rw
  - share
  - ssl
  - media
hassio_api: true
auth_api: true
docker_api: true
host_network: true
host_pid: true
apparmor: false
image: "ghcr.io/conrad784/{arch}-hassio-telegraf"