---
name: Telegraf
version: 0.0.5
slug: hassio_telegraf
description: Export system metrics with telegraf
url: https://github.com/conrad784/hassio-telegraf
panel_icon: mdi:speedometer
startup: services
arch:
  - amd64
map:
  - addons
  - backup
  - config:rw
  - share
  - ssl
  - media
hassio_api: true
auth_api: true
docker_api: true
host_network: true
host_pid: true
apparmor: false
image: "ghcr.io/conrad784/{arch}-hassio-telegraf"